### ISSUE TITLE
Create automation to mirror the Eclipse OMR project into the master branch

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9-omr#3]
The Eclipse OMR project (https://github.com/eclipse/omr) is the upstream for the openj9-omr repo.  Currently, this repo is updated manually by committers.  

We need an automated build that will sync the Eclipse OMR master branch into the openj9-omr master branch.  These two branches should always be the same.

**Comment by DanHeidinga** [comment]
FYI @AdamBrousseau

**Comment by DanHeidinga** [comment]
Eclipse bugzilla to request a bot account: https://bugs.eclipse.org/bugs/show_bug.cgi?id=522322

**Comment by AdamBrousseau** [comment]
Build is ready [here](https://ci.eclipse.org/openj9/view/Infrastructure/job/Mirror-OMR-to-OpenJ9-OMR/). Once our bot user has proper permissions it should work. WIll need to determine how to trigger the job. I propose we request a webhook at eclipse/omr to trigger our build.

**Comment by AdamBrousseau** [comment]
This is working now [here](https://ci.eclipse.org/openj9/job/Mirror-OMR-to-OpenJ9-OMR/)

@charliegracie can you open an eclipse bug to have a webhook created at eclipse/omr to poke the job every time code is pushed.
url is: https://ci.eclipse.org/openj9/job/Mirror-OMR-to-OpenJ9-OMR/build?token=OPENJ9

In the meantime I setup the job to run every 15 minutes.

My next action is to move the pipeline script to the openj9 repo

**Comment by AdamBrousseau** [comment]
Pipeline script merged into the repo and job reconfigured to pull script from eclipse/openj9/master
