### ISSUE TITLE
Create automated build to validate master branch and promote to openj9 branch

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9-omr#4]
Code from the upstream OMR repo is synchronized into the master branch.  Once there, we need an automated build that will validate it with openj9 repo and merge it into the openj9-omr repo's openj9 branch.

**Comment by DanHeidinga** [comment]
FYI @AdamBrousseau

**Comment by AdamBrousseau** [comment]
Token needed for API calls to GitHub from Jenkins.
Added requirements to the existing (bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=522322) from #3

**Comment by AdamBrousseau** [comment]
Previous comment is actually required for PullRequest builds, not the build that this issue is for (my mistake for confusing the issues). This issue is for the "OMR Acceptance" build which we can now implement since #3 is resolved. I will get going on this today.

**Comment by AdamBrousseau** [comment]
Added tagging in the promote job.
Tag format:
Name:
```omr_merge_YYYYMMDD_HHMMSS```
Annotation:
```
OMR: <OMR_SHA>
OpenJ9: <OPENJ9_SHA>
OpenJDK: <OPENJDK_SHA>
```

Everything seems to be working now. We have had 3 levels promote through without issue.

**Comment by AdamBrousseau** [comment]
@DanHeidinga I think we can close this as complete

**Comment by DanHeidinga** [comment]
Agreed.  Thanks for all your work on this @AdamBrousseau - not only on the scripting but working through getting the web hooks, etc configured. Much appreciated!
