### ISSUE TITLE
Track merges from master -> openj9 branch

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9-omr#5]
While we have an automated build to sync from Eclipse OMR to the openj9-omr repo's `master` branch, there isn't yet automation to test and promote to the `openj9` branch.

A verbose and overly careful process for doing this:

$ git fetch openj9-omr    // fetch from the remote
$ git checkout master
$ git rebase openj9-omr/master // ensure local master is up to date
$ git log --oneline // get listing of commits to determine which to promote to the openj9 branch
$ git checkout openj9
$ git rebase master // This MUST be a fast forward merge.  If it's not, there's a problem
$ git log --oneline // ensure history is the same as above
$ git reset --hard sha_of_chosen_commit
$ git push openj9-omr openj9 // format is <remote> <branch> and branch must be openj9

Use this item to track when the openj9 branch is updated.

**Comment by DanHeidinga** [comment]
heidingas-mbp:omr heidinga$ git push openj9-omr openj9
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/eclipse/openj9-omr.git
   617de127..03661455  openj9 -> openj9

**Comment by DanHeidinga** [comment]
heidingas-mbp:omr heidinga$ git push openj9-omr openj9
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/eclipse/openj9-omr.git
   03661455..c10a67a9  openj9 -> openj9

**Comment by 0xdaryl** [comment]
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/eclipse/openj9-omr.git
   c10a67a..3271be8  openj9 -> openj9

**Comment by DanHeidinga** [comment]
heidingas-mbp:omr heidinga$ git push openj9-omr openj9
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/eclipse/openj9-omr.git
   3271be89..b746dab4  openj9 -> openj9

**Comment by DanHeidinga** [comment]
heidingas-mbp:omr heidinga$ git push openj9-omr openj9
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/eclipse/openj9-omr.git
   b746dab4..2d351f73  openj9 -> openj9

**Comment by DanHeidinga** [comment]
Closing this as the automated build is now in place.

When code is promoted from `master` -> `openj9` branch, the automated build adds a tag.  See https://github.com/eclipse/openj9-omr/issues/4#issuecomment-332492242 for details.

**Comment by DanHeidinga** [comment]
Closing this as well.
